### ISSUE TITLE
Prometheus annotations missing with KogitoRuntime

### ISSUE THREAD

**Issue by aramashkan** [kiegroup/kogito-operator#1240]
### Describe the bug

According to [this](https://github.com/kiegroup/kogito-operator/blob/72922097dc2895e64caf4fc895a9dba0dca1f20d/core/framework/image_metadata.go) code (was added in KOGITO-290) i suppose that prometheus annotation will be passed from image docker labels to produced k8s resources (Pod\Service). I have image docker.io/antram/kogito-operator-test:2.0.0 with prometheus labels:
```
[
    {
        "Id": "sha256:fb5d8f69a8e98bff8fa2cf0bb6ae81ccf650e20fd1f70815cf65b624f58fd34c",
        "RepoTags": [
            "antram/kogito-operator-test:2.0.0"
        ],
        "RepoDigests": [
            "antram/kogito-operator-test@sha256:3559817838c75a5601be0084a784007caf7f0c83f64911c92b9d473cbfc1c7fa"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2022-07-06T12:07:46.605776Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANGUAGE=en_US:en",
                "JAVA_HOME=/usr/lib/jvm/zulu17-ca-amd64",
                "LC_ALL=en_US.UTF-8",
                "LANG=en_US.UTF-8"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": {},
            "WorkingDir": "/home/jboss",
            "Entrypoint": [
                "java",
                "-Djava.util.logging.manager=org.jboss.logmanager.LogManager",
                "-jar",
                "quarkus-run.jar"
            ],
            "OnBuild": null,
            "Labels": {
                "prometheus.io/path": "/q/metrics",
                "prometheus.io/port": "8080",
                "prometheus.io/scrape": "true"
            }
        },

```
configuration for operator:
```
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: kogito-operator-test
spec:
  replicas: 1
  image: docker.io/antram/kogito-operator-test:2.0.0
  resources:
    requests:
      cpu: 20m
      memory: "320Mi"
    limits:
      cpu: "1"
      memory: "400Mi"
```
Gradle project with example process got 
```implementation("org.kie.kogito:kogito-addons-quarkus-monitoring-prometheus")```
builded with:
```implementation("io.quarkus:quarkus-container-image-jib")```

### Expected behavior

Produced pod or service by kogito operator contains prometheus annotations:
```
  annotations:
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
```

### Actual behavior

Missing prometheus annotations

### How to Reproduce?

1. Applying example configuration

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### Kogito Operator version or git rev

https://github.com/kiegroup/kogito-operator/releases/download/v1.23.0/kogito-operator.yaml

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.4.2 ------------------------------------------------------------  Build time:   2022-03-31 15:25:29 UTC Revision:     540473b8118064efcc264694cbcaa4b677f61041  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.1 (Azul Systems, Inc. 17.0.1+12-LTS) OS:           Mac OS X 10.15.3 x86_64

### Additional information

Maybe i'm missing something and choose not correctly way ?  Looked in operator's crd , but not found for passing annotations manually.

**Comment by spolti** [comment]
I am closing this issue due inactivity, feel free to reopen :)
