### ISSUE TITLE
v1.2.0 does not respect NAMESPACE variable.

### ISSUE THREAD

**Issue by jarradh** [kiegroup/kogito-operator#758]
Attempting to execute 
```
NAMESPACE=mynamespace
VERSION=v1.2.0
kubectl apply -n "${NAMESPACE}" -f "https://github.com/kiegroup/kogito-cloud-operator/releases/download/${VERSION}/kogito-operator.yaml"
```
results in the following error
```
You must pass '--namespace=kogito-operator-system' to perform this operation.
the namespace from the provided object "kogito-operator-system" does not match the namespace "mynamespace".
```
Using `NAMESPACE=kogito-operator-system` results in a valid deloyment

**Comment by Kaitou786** [comment]
Hi, @jarradh thank you for opening the issue :)
The [YAML installer](https://github.com/kiegroup/kogito-cloud-operator/blob/master/kogito-operator.yaml) we have deploys the operator in its own namespace `kogito-operator-namespace` and watches all the objects in the whole cluster(cluster-wide deployment). So the `NAMESPACE` var is not respected, it is hard-coded in the [yaml itself](https://github.com/kiegroup/kogito-cloud-operator/blob/master/kogito-operator.yaml#L2471).  I agree we need to update our README and describe more about the behaviour of this installation.
