### ISSUE TITLE
Default pulling Image location is pointed to quay.io, what to do if I have to pull image from ECR. 

### ISSUE THREAD

**Issue by aajaykrishnareddy** [kiegroup/kogito-operator#777]
I'm trying to deploy the kogito app (https://github.com/kiegroup/kogito-examples/tree/stable/process-knative-quickstart-quarkus) on knative using kogito-operator. I modified the image loacation to private ECR repository in "process-knative-quickstart-quarkus.yaml". But while deploying still its appending quay.io to the ecr image url because of which it is failing.
ex: 
in yaml - 123456789.abc.ecr.us-east-1.amazonaws.com/process-knative-quickstart-quarkus
actual logs -  quay.io/123456789.abc.ecr.us-east-1.amazonaws.com/process-knative-quickstart-quarkus (this is inavalid as it appended quay.io)

**Comment by spolti** [comment]
Hey, do you mind to share how have you configured it? 
This should allow you to configure custom images:

```
  image: domain: quay.io/kiegroup/kogito-travels:tag
```

**Comment by aajaykrishnareddy** [comment]
I'm using the yaml files form this directory 'https://github.com/kiegroup/kogito-examples/tree/stable/process-knative-quickstart-quarkus/operator/kubernetes'. Just made one change in "process-knative-quickstart-quarkus.yaml" where I modified the image URL something like this
image: 123456789.abc.ecr.us-east-1.amazonaws.com/process-knative-quickstart-quarkus

**Comment by Kaitou786** [comment]
Hi, @aajaykrishnareddy our operator right now thinks that the image would bring three parts:
```
<some_repo>/<some_namespace>/<some_image>
Example: quay.io/kiegroup/kogito-travels
```.
 Since the image that you used has only two parts (separator `/`) so the operator thinks that you forgot to give the `repo` so it appends the default `quay.io` as the repo.
 If possible can you try giving the image in the above pattern, :)

**Comment by spolti** [comment]
Hi @aajaykrishnareddy, were you able to test it as suggested By Kaitou in the comment above?

**Comment by aajaykrishnareddy** [comment]
Hi @spolti, it didn't work for me. And as we got the quay repo setup, so was working with that.

**Comment by ricardozanini** [comment]
@sutaakar @vaibhavjainwiz I believe we already solved this issue? Could you guys please take a look? If not, can you kindly open a new JIRA?

**Comment by sutaakar** [comment]
reported as https://issues.redhat.com/browse/KOGITO-5390
